**Numpy** - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.

In [1]:
# Python 2 and 3 compatibility
from __future__ import (absolute_import, division,
                        print_function, unicode_literals)
# отключим предупреждения Anaconda
import warnings
warnings.simplefilter('ignore')
import numpy as np

In [3]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

Такой массив может содержать:
- значения физических величин в разые моменты времени при моделировании
- значения сигнала, измеренного прибором
- интенсивности пикселов 
- 3D координаты объектов, полученных, например, при МРТ
- ...


**Зачем NumPy:** Эффективность базовых операций

In [5]:
L = range(1000)
L

range(0, 1000)

In [7]:
%timeit [i**2 for i in L]

588 µs ± 24.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
a = np.arange(1000)
a[:20]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
%timeit a**2

2.66 µs ± 299 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Создание массивов

* **1-D**:


In [11]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [12]:
a.ndim

1

In [13]:
a.shape

(4,)

In [14]:
len(a)

4

* **2-D, 3-D, ...**:


In [15]:
a = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
a.ndim

2

In [17]:
a.shape

(2, 3)

In [19]:
len(a) # returns the size of the first dimension

2

In [20]:
c = np.array([
    [[1], [2]], 
    [[3], [4]]
])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [21]:
c.ndim

3

In [22]:
c.shape

(2, 2, 1)

In [23]:
len(c)

2

## Методы для создания массивов

На практике мы редко добавляем элементы по одному


- Равномерно распределенные элементы:


In [24]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b = np.arange(1, 9, 2) # start, end (exclusive), step
b

array([1, 3, 5, 7])

- по числу элементов:


In [26]:
c = np.linspace(0, 1, 6) # start, end, num-points
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [27]:
d = np.linspace(0, 1, 5, endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

- Часто встречающиеся массивы:


In [29]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
d = np.diag(np.array([1, 2, 3, 4, 5]))
d

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

* `np.random` генерация случайных чисел (Mersenne Twister PRNG):

In [36]:
a = np.random.rand(4) # uniform in [0, 1]
a

array([0.09501723, 0.49470634, 0.69952163, 0.09452155])

In [37]:
b = np.random.randn(4)      # Gaussian
b  

array([ 0.92407486, -1.07224481,  0.84931465,  0.56211238])

In [38]:
np.random.seed(42)        # Setting the random seed